workflows:
  flutter-test:
    name: Flutter Integration Tests
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: 16.4

    scripts:
      - name: Make script executable
        script: |
          chmod +x ./run_tests.sh

      - name: Launch emulator
        script: |
          flutter emulators --launch apple_ios_simulator

      - name: Run tests script
        script: |
          ./run_tests.sh