name: rick_and_morty_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  cached_network_image: ^3.4.1
  http: ^1.5.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.11
  test: ^1.25.2
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

