name: Flutter CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      - name: Start Android Emulator and Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          emulator-options: '-no-window -no-snapshot -noaudio -no-boot-anim -gpu host'
          script: |
            echo "Waiting for emulator to be fully booted..."
            
            adb wait-for-device
            adb shell while [[ -z $(getprop sys.boot_completed) ]]; do sleep 5; done
            
            EMULATOR_ID=$(adb devices | grep emulator | cut -f1)
            
            if [ -z "$EMULATOR_ID" ]; then
              echo "Error: Emulator ID could not be found after boot."
              exit 1
            fi
            
            echo "Found emulator: $EMULATOR_ID"
            
            ./run_tests.sh "$EMULATOR_ID"