name: Flutter CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v1
        with:
         java-version: "17.0.16"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'
      
      - name: Make script executable
        run: chmod +x run_tests.sh
      
      - name: Setup Android SDK
        run: |
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/emulator" >> $GITHUB_PATH
      
      - name: Kill ADB server
        run: adb kill-server

      - name: Start Android Emulator and Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          script: |
            echo "Waiting for emulator to be ready..."
            adb wait-for-device
            adb shell while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done
            echo "Emulator is ready!"
            ./run_tests.sh